version: "3"

services:
  web:
    image: nginx
    build: .
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: [nginx-debug, "-g", "daemon off;"]
